on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Environment'
        required: true
        default: 'development'
        
name: "Linux Test ${{ github.event.inputs.project }}"

jobs:
  test_build:
    runs-on: ubuntu-latest
    name: Build a project using Arduino CMake Toolchain
    steps:
    - run: echo "${{ github.event.inputs.project }}"
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Checkout the Arduino CMake Toolchain repository
      uses: actions/checkout@v2
      with:
        repository: a9183756-gh/Arduino-CMake-Toolchain
        path: Arduino-CMake-Toolchain
        ref : release-1.1-dev
    - run: mkdir  ${{ github.workspace }}/build
    - name: Build the example project of the toolchain
      # uses: arduino-cmake-toolchain/test-build@v0.2
      uses: ./
      with:
        CMAKE_GENERATOR: 'Unix Makefiles'
        ARDUINO_TOOLCHAIN_DIR:  ${{ github.workspace }}/Arduino-CMake-Toolchain
        ARDUINO_PROJECT_DIR :  ${{ github.workspace }}/Arduino-CMake-Toolchain/Examples/01_hello_world
        ARDUINO_BUILD_DIR :  ${{ github.workspace }}/build
        ARDUINO_BOARD: arduino.avr.uno
        ARDUINO_BOARD_MANAGER_URL : 'https://downloads.arduino.cc/packages/package_index.json'
